seed: 0

run_dir: ./run_results/
experiment_name: smac_mappo

lr: 5e-4
critic_lr: 5e-4

episode_length: 400
ppo_epoch: 5
log_interval: 10
attn_size: 128


use_recurrent_policy: true
use_joint_action_loss: false
use_valuenorm: true
use_adv_normalize: true
use_value_active_masks: false

wandb_entity: openrl-lab

vec_info_class:
  id: "SMACInfo"