seed: 0
lr: 1e-7
critic_lr: 1e-7
run_dir: ./run_results/
log_interval: 1
use_valuenorm: true
use_adv_normalize: true
wandb_entity: "openrl-lab"
ppo_epoch: 5
episode_length: 128
num_mini_batch: 20

hidden_size: 1

use_deepspeed: true
use_fp16: false
use_offload: false
deepspeed_config: ds_config.json

model_path: rajkumarrrk/gpt2-fine-tuned-on-daily-dialog
env:
  args: {
    'tokenizer_path': 'gpt2',
    'data_path': 'daily_dialog',
  }
vec_info_class:
  id: "NLPVecInfo"
reward_class: 
  id: "NLPReward"
  args: { 
    "use_deepspeed": true,
    "ref_ds_config": "eval_ds_config.json",
    "ref_model": "rajkumarrrk/gpt2-fine-tuned-on-daily-dialog",
    "intent_ds_config": "eval_ds_config.json",
    "intent_model": "rajkumarrrk/roberta-daily-dialog-intent-classifier",
  }
    