{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
package:
  name: openrl
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  script: python -m pip install . -vv
  entry_points:
    - openrl = openrl.cli.cli:run

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - openrl

about:
  home: https://github.com/OpenRL-Lab/openrl
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: OpenRL is a reinforcement learning framework (https://github.com/OpenRL-Lab/openrl).
  description: Please refer to https://openrl-docs.readthedocs.io/en/latest/
  dev_url: https://github.com/OpenRL-Lab/openrl
  doc_url: Please refer to https://openrl-docs.readthedocs.io/en/latest/
  doc_source_url: https://github.com/OpenRL-Lab/openrl-docs/
